### ISSUE TITLE
Add eCommerce attributes such as price or brand name as a template variable

### ISSUE THREAD

**Issue by atimmer** [Yoast/wpseo-woocommerce#158]
See https://github.com/Yoast/wordpress-seo/issues/5161

**Comment by iamazik** [comment]
Please inform the customer of conversation # 143101 when this conversation has been closed.

**Comment by jdevalk** [comment]
Please add short description as a template variable too.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 185269 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 183957 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 190457 when this conversation has been closed.

**Comment by moorscode** [comment]
I have contacted Ines on WPNL Slack with the request for the WooCommerce Brands plugin.

**Comment by iamazik** [comment]
If possible, please also consider adding the product SKU as a template variable.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 220354 when this conversation has been closed.

**Comment by amboutwe** [comment]
Most of the WooCommerce variables can be made using the custom field/taxonomy option we already have.

SKU = %%cf__sku%%
Short Description = %%excerpt%%
Price = %%cf__price%% (outputs just the number though, not the currency sign)
Brand = %%ct_product_brand%% (using WooCommerce Brands Version 1.4.3)

Note: I added these (except price since that's not a great output) to the KB article.

**Comment by moorscode** [comment]
The WooCommerce Brands plugin can be found in the company drive folder "Common Premium Plugins"
