### ISSUE TITLE
Add breadcrumbs override compatibility for Storefront and WooThemes

### ISSUE THREAD

**Issue by moorscode** [Yoast/wpseo-woocommerce#298]
We have fixed the Breadcrumbs override for WooCommerce default hooks in https://github.com/Yoast/wpseo-woocommerce/issues/150.
We also want to make sure this happens on the WooThemes and Storefront themes.

Hooks:  `woo_main_before` & `storefront_before_content`

**Comment by iamazik** [comment]
Please inform the customer of conversation # 459360 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 463637 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 472961 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 482174 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 483317 when this conversation has been closed.

**Comment by Pcosta88** [comment]
We ask users to add a code snippet in order to override the WooThemes Breadcrumbs https://kb.yoast.com/kb/replace-woothemes-breadcrumbs-by-yoast-breadcrumbs/

But it fails to do so and outputs two sets of breadcrumbs instead of overriding it:

**1. Add in code snippet to functions.php:** https://gist.github.com/tacoverdo/ed594adc1f91776eec49682ba2ad89a3#file-yoast_seo_breadcrumbs_replace_woocommerce_woothemes-php

![Screen Shot 2019-04-24 at 9 43 45 AM](https://user-images.githubusercontent.com/8238074/56664078-757f6200-6675-11e9-8942-acd398be362a.png)

2.See two sets of breadcrumbs outputted on a product pages

<img width="530" alt="Screen_Shot_2019-04-24_at_9_44_24_AM" src="https://user-images.githubusercontent.com/8238074/56664385-05bda700-6676-11e9-8b82-4c21c64829cb.png">


**Tech Specs**
WooCommerce: 3.6.1
Storefront: 2.4.5
Yoast: 11

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 497523 when this conversation has been closed.

**Comment by rmarcano** [comment]
It seems that the previous code snippet is not working to remove the breadcrumbs. The following code does work:

```
// Remove WooCommerce Breadcrumbs 
add_action( 'init', 'storefront_remove_storefront_breadcrumbs' );
 
function storefront_remove_storefront_breadcrumbs() {
   remove_action( 'storefront_before_content', 'woocommerce_breadcrumb', 10 );
}
```

**Comment by iamazik** [comment]
Please inform the customer of conversation # 543385 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 572377 when this conversation has been closed.

**Comment by jdevalk** [comment]
Decision: we're not going to fix this.
