### ISSUE TITLE
Different warnings for empty products

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#560]
1. Install and activate Yoast SEO 13.3.
2. Install and activate Woocommerce 4.0.1.
3. Install and activate SEO Woocommerce 12.6.2.
4. Create empty product, do not add price.
5. Browse to product, add review, you get:

<img width="743" alt="Screenshot 2020-03-27 at 07 32 27" src="https://user-images.githubusercontent.com/19681708/77728605-21a39880-6ffd-11ea-8004-6df1a5ad871f.png">

```
Notice: Undefined index: offers in /srv/www/wordpress-two/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 146
Warning: Invalid argument supplied for foreach() in /srv/www/wordpress-two/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 146
```

6. Now install and activate Yoast SEO 13.4 RC3.
7. Install and activate SEO Woocommerce 12.7 RC1.
8. Create empty product, do not add price.
9. Browse to product, add review, you get:

<img width="612" alt="Screenshot 2020-03-27 at 07 34 41" src="https://user-images.githubusercontent.com/19681708/77728757-7515e680-6ffd-11ea-8819-c72e27c61b46.png">

```
Warning: Invalid argument supplied for foreach() in /srv/www/local/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 185
Warning: Invalid argument supplied for foreach() in /srv/www/local/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 149
Reviews (1)
```

I have not found any previously created issue for the problem that is encountered in step 5, but I do find strange the difference in warnings which are given now.

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 13.4 RC3
* Yoast SEO for WooCommerce version: 12.7 RC1

**Comment by afercia** [comment]
For future testing it's important to keep in consideration what WooCommerce does.

WooCommerce outputs the product Schema only if some "required" data are set. See

https://github.com/woocommerce/woocommerce/blob/1926a5042622980ce9b520e63b8cc30d917d4a07/includes/class-wc-structured-data.php#L323-L326

So there must be at least the `aggregateRating` markup, or the `offers` markup, or the `review` markup.

When a product as an empty price _and no reviews_, none of the required data is present. WooCommerce doesn't output the Schema. This may actually "hide" potential errors in our code because The Schema-related code doesn't run.

By adding a review on a product with no price as in the test instructions, the Schema is output thus the error is shown.

**Comment by afercia** [comment]
Regarding the different warnings:

`filter_sales()` was added in 12.7 so there's one more `foreach` statement that tries to loop on a non-set value. That explains why on 12.7 there are two warnings and in  12.6.2 there's just one warning.

Regarding the PHP _notice_,  in my testing I'm getting the notice on both 12.6.2 and 12.7.
