### ISSUE TITLE
Fatal Error: Call to a member function image_output() on null 

### ISSUE THREAD

**Issue by zandergrin** [Yoast/wpseo-woocommerce#613]
### What did you expect to happen?
Product page to load

### What happened instead?
Error: 

`http://site.com/content/uploads/2016/11/1IMAGENAMEjpg
Fatal error: Uncaught Error: Call to a member function image_output() on null in /var/www/site/public/content/plugins/wpseo-woocommerce/wpseo-woocommerce.php:527 Stack trace: #0 /var/www/site/public/wp/wp-includes/class-wp-hook.php(287): Yoast_WooCommerce_SEO->og_enhancement() #1 /var/www/site/public/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /var/www/site/public/wp/wp-includes/plugin.php(544): WP_Hook->do_action(Array) #3 /var/www/site/public/wp/wp-includes/plugin.php(660): do_action_ref_array('wpseo_opengraph', Array) #4 /var/www/site/public/content/plugins/wordpress-seo/src/integrations/front-end/backwards-compatiblity.php(60): do_action_deprecated('wpseo_opengraph', Array, '14.0', 'wpseo_frontend_...') #5 /var/www/site/public/wp/wp-includes/class-wp-hook.php(287): Yoast\WP\SEO\Integrations\Front_End\Backwards_Compatibility->call_wpseo_opengraph('') #6 /var/www/site/public/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) in /var/www/site/public/content/plugins/wpseo-woocommerce/wpseo-woocommerce.php on line 527`

Only found on one product  - itas an image and is ostensibly no different from any other on the site

### How can we reproduce this behavior?
Honestly - not sure. I replaced all the images in the gallery - and the error still occurred, it only seems to be on one page of the site.If I rebuilt the product with the exact same content, then no error. Rebuilt thumbnails, and edited all content. Repaired database. I also echoed out the elements that are being called and everything seems to be fine.

Can you provide a link to a page which shows this issue?
Sorry - I had to replace the page as it is a live site. I rolled back to the prev version of the plugin and no issue. 

### Technical info
* WordPress version: 5.4.1
* Yoast SEO version: 14.2
* Yoast SEO for WooCommerce version: 13.2

**Comment by Djennez** [comment]
I'm not sure which version you were running, but I doubt it was 13.2. `wpseo-woocommerce.php` has no more than 100 lines since 12.5, so it's hard to see how an error could occur on a 500+ line. 

Anyway, as it's not reproducible, and you've been able to fix it yourself, I see no reason to keep this open. But if you, or anyone else, runs into this issue again, please do let me know and we'll look into it.

**Comment by zandergrin** [comment]
I thought it would be worth mentioning - because commenting out the cited line (527) resolved the issue, as does reverting the plugin to a former version or disabling it entirely.

Note I also checked all the other plugins by disabling them for a conflict - there was none. It may be a conflict with the theme - which I didn’t check to be honest.

I can get the page up on a staging site if you like - but all you’ll see is the error I copy and pasted above.

**Comment by Djennez** [comment]
@zandergrin please make 100% sure that you're running the latest version. Manually remove and reinstall the plugin if necessary. Again: in the latest version of the WPSEO WooCommerce plugin, `/var/www/site/public/content/plugins/wpseo-woocommerce/wpseo-woocommerce.php` should have no more than [61 lines](https://github.com/Yoast/wpseo-woocommerce/blob/13.2/wpseo-woocommerce.php). Since we don't support older versions of the plugin, this is a non-issue. If the problem persists with 13.2, I would very much like to know the error (and reproduction steps if possible).
