### ISSUE TITLE
WooCommerce SEO: PHP 8.1 improvements

### ISSUE THREAD

**Issue by enricobattocchi** [Yoast/wpseo-woocommerce#918]
Address the improvements listed in:
https://docs.google.com/spreadsheets/d/1Vo857mjQs2JbVR7wyYrdFTHPJzGKSRx9ja1sSTbLsJ8/edit#gid=637354147

**Comment by 37Rb** [comment]
Tired of seeing this warning many times per day. As a temp workaround I changed

```php
                $indexable            = $indexable_repository->find_by_id_and_type( $product_id, 'post' );

                return $indexable->open_graph_image_source === 'set-by-user';
```

to

```php
                $indexable            = $indexable_repository->find_by_id_and_type( $product_id, 'post' );
                if ( is_bool( $indexable ) ) {
                        return false;
                }

                return $indexable->open_graph_image_source === 'set-by-user';
```

**Comment by jrfnl** [comment]
@37Rb This issue is about something else than what you're talking about. Please open a dedicated issue for your problem with additional information, like the deprecation notice you are seeing, preferably with a backtrace, the PHP version you are using, the WP version, the plugins list + versions etc
